name: Test Nest

on:
  push:
    branches:
      - master
      - main
      - v*
      - test
      - dev
      - feature/**
  pull_request:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [ 10.x, 12.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
  test:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        node-version: [ 10.x, 12.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Copy .env file
        run: 'echo "$ENV_FILE" > ./.env'
        shell: bash
        env:
          ENV_FILE: ${{ secrets.PRODUCTION_ENV_FILE }}
      - run: npm ci
      - run: npm test
