name: Test Nest

on:
  pull_request:
    branches:
      - master
      - main
      - main/*
      - feature/*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [ 22.14 ]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
  test:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        node-version: [ 22.14 ]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Import Secrets from Infisical
        uses: Infisical/secrets-action@v1.0.9
        with:
          method: "universal"
          identity-id: "24be0d94-b43a-41c4-812c-1e8654d9ce1e"
          domain: "https://eu.infisical.com"
          env-slug: "dev"
          project-slug: "themepark-planner-k-cq1"
          export-type: "file"
          client-id: ${{ secrets.INFISICAL_CLIENT_ID }}
          client-secret: ${{ secrets.INFISICAL_CLIENT_SECRET }}
      - run: npm ci
      - run: npm test
