export interface SeaworldBaseItem {
  'IsMfoOpen': boolean,
  'Id': string,
  'Coordinate': {
    'Latitude': number,
    'Longitude': number
  },
  'Name': string,
  'ShortDescription': string,
  'LongDescription': string,
  'Type': 'Shows' | 'Animal Experiences' | 'Attractions' | 'Dining' | 'Restrooms' | 'Rides' | 'Services' | 'Shops' | 'Venues',
  'SubType': 'AED' | 'ATM' | 'Smoking Area' | 'Viewing Interaction' | 'Tours' | 'Restaurant' | 'Bar' | 'Quick Bites' | 'Restrooms' | 'Water Ride' | 'Family Friendly Ride' | 'Coaster' | 'Wet Play Area' | 'Aerial Ride' | 'Meet and Greets' | string | null,
  'ImageId': string,
  'ImageUrl': string,
  'AdditionalDetailsPdfId': null,
  'AdditionalDetailsPdfUrl': null,
  'GFPId': string,
  'GFP': {
    'ShortDescription': null,
    'LongDescription': null,
    'Disclaimer': null,
    'ImageUrl': '',
    'CallToActionLabel': null,
    'SubtitleText': null,
    'SellingGroup': [],
    'GFPId': 'a3e38fca-a7c2-42e7-ae8d-d6affd941fc2',
    'Name': null
  },
  'Category': {
    'CategoryId': string,
    'CategoryName': string,
    'CatalogId': null,
    'Subcategory': null
  },
  'Tags': [],
  'TagIds': [],
  'HeadlineImageId': null,
  'ListingImageId': null,
  'LogoImageId': null,
  'HeadlineImageUrl': null,
  'ListingImageUrl': null,
  'LogoImageUrl': null,
  'Description': null,
  'PoolType': null,
  'MinimumHeight': number,
  'AccessibilityNotes': null,
  'SensoryLevel': {
    'Touch': 0,
    'Taste': 0,
    'Sound': 0,
    'Smell': 0,
    'Sight': 0
  },
  'ProductCatalogId': null,
  'PassmemberProductCatalogId': null,
  'SupportsAllDayDining': boolean,
  'SpecialtyDining': boolean,
  'AttractionId': string | null,
  'Allergens': null,
  'MobileOrderingStoreId': null,
  'OnlineOrderingEnabled': boolean,
  'OnlineOrderingUrl': string | null,
  'StaticMenuUrl': string | null | '',
  'RideType': 'Coaster' | null,
  'ShowType': null | 'Show Type 1' | '',
  'ShowTimes': {
    'StartDateTime': string,
    'EndDateTime': string,
    'StartTime': string,
    'EndTime': string
  }[],
  'SlideType': null
}
